
import type { MenuItem, Order, Review, BrandInfo, Promotion, Address } from './types';

export const brandInfo: BrandInfo = {
  name: 'CulinaPreOrder',
  logoUrl: '',
  phone: '123-456-7890',
  address: {
    doorNumber: '123',
    apartmentName: 'Foodie Building',
    area: 'Flavor Town',
    city: 'Metropolis',
    state: 'Culinary State',
    pincode: '12345',
  },
  about: 'CulinaPreOrder was born from a passion for exquisite food and a desire to make fine dining accessible. We believe in quality ingredients, handcrafted recipes, and the convenience of pre-ordering, allowing you to enjoy gourmet meals without the wait.',
  businessHours: {
    status: 'open',
    message: 'We are temporarily closed. Please check back later!',
  },
  youtubeUrl: '',
  instagramUrl: '',
  allowOrderUpdates: true,
  theme: {
    primaryColor: '30 85% 67%',
    backgroundColor: '28 71% 92%',
    accentColor: '14 66% 62%',
    fontHeadline: 'Alegreya',
    fontBody: 'Alegreya',
    borderRadius: 0.5,
    backgroundImageUrl: '',
  },
};

const aliceAddress: Address = {
    doorNumber: '4A',
    apartmentName: 'Wonderland Apts',
    area: 'Rabbit Hole District',
    city: 'Curious City',
    state: 'Imagi Nation',
    pincode: '12345',
    latitude: 34.0522,
    longitude: -118.2437,
};

const dianaAddress: Address = {
    doorNumber: '100',
    apartmentName: 'Olympus Towers',
    area: 'Themyscira Plaza',
    city: 'Paradise Island',
    state: 'Amazonia',
    pincode: '23456'
};

const charlieAddress: Address = {
    doorNumber: '22B',
    apartmentName: 'Chocolate Factory',
    area: 'Sweet Street',
    city: 'Confectionville',
    state: 'Sugarland',
    pincode: '34567',
    latitude: 40.7128,
    longitude: -74.0060,
};

const eveAddress: Address = {
    doorNumber: '1',
    apartmentName: 'Garden House',
    area: 'Eden Estates',
    city: 'First City',
    state: 'Genesis',
    pincode: '45678'
};

const bobAddress: Address = {
    doorNumber: 'B2',
    apartmentName: 'Builder Complex',
    area: 'Construct Lane',
    city: 'Tool-Town',
    state: 'Handy State',
    pincode: '56789'
};

const frankAddress: Address = {
    doorNumber: 'C-3',
    apartmentName: 'Castle Apartments',
    area: 'Kingdom Valley',
    city: 'Nobleburg',
    state: 'Regalia',
    pincode: '67890',
    latitude: 51.5074,
    longitude: -0.1278,
};

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Bruschetta',
    description: 'Toasted bread with tomatoes, garlic, and basil.',
    price: 8.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'bruschetta appetizer',
    category: 'Appetizers',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: '2',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, and basil.',
    price: 10.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'caprese salad',
    category: 'Appetizers',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: '3',
    name: 'Spaghetti Carbonara',
    description: 'Pasta with eggs, cheese, pancetta, and pepper.',
    price: 15.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'spaghetti carbonara',
    category: 'Main Courses',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: '4',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomatoes, mozzarella, and basil.',
    price: 14.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'margherita pizza',
    category: 'Main Courses',
    isAvailable: true,
    isFeatured: true,
  },
    {
    id: '5',
    name: 'Grilled Salmon',
    description: 'Served with asparagus and lemon butter sauce.',
    price: 22.00,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'grilled salmon',
    category: 'Main Courses',
    isAvailable: true,
    isFeatured: true,
  },
  {
    id: '6',
    name: 'Tiramisu',
    description: 'Coffee-flavored Italian dessert.',
    price: 7.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'tiramisu dessert',
    category: 'Desserts',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: '7',
    name: 'Panna Cotta',
    description: 'Sweetened cream thickened with gelatin.',
    price: 6.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'panna cotta',
    category: 'Desserts',
    isAvailable: true,
    isFeatured: false,
  },
  {
    id: '8',
    name: 'Mineral Water',
    description: 'Still or sparkling water.',
    price: 3.00,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'water bottle',
    category: 'Drinks',
    isAvailable: true,
    isFeatured: false,
  },
    {
    id: '9',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice.',
    price: 5.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'orange juice',
    category: 'Drinks',
    isAvailable: true,
    isFeatured: false,
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    customerId: 'user-alice',
    customerName: 'Alice',
    address: aliceAddress,
    orderDate: '2023-10-25',
    pickupDate: '2023-10-26',
    pickupTime: '18:30',
    status: 'Completed',
    total: 32.48,
    items: [
      { id: '3', name: 'Spaghetti Carbonara', price: 15.99, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '6', name: 'Tiramisu', price: 7.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    reviewId: 'REV-001',
    updateRequests: [],
  },
  {
    id: 'ORD-002',
    customerId: 'user-diana',
    customerName: 'Diana',
    address: dianaAddress,
    orderDate: '2023-11-14',
    pickupDate: '2023-11-15',
    pickupTime: '19:00',
    status: 'Confirmed',
    total: 25.00,
    items: [
      { id: '4', name: 'Margherita Pizza', price: 14.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '2', name: 'Caprese Salad', price: 10.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    updateRequests: [],
  },
  {
    id: 'ORD-003',
    customerId: 'user-charlie',
    customerName: 'Charlie',
    address: charlieAddress,
    orderDate: '2023-11-30',
    pickupDate: '2023-12-01',
    pickupTime: '12:00',
    status: 'Pending',
    total: 27.50,
    items: [
      { id: '5', name: 'Grilled Salmon', price: 22.00, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '9', name: 'Fresh Orange Juice', price: 5.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    updateRequests: [],
  },
   {
    id: 'ORD-004',
    customerId: 'user-eve',
    customerName: 'Eve',
    address: eveAddress,
    orderDate: '2024-01-04',
    pickupDate: '2024-01-05',
    cancellationDate: '2024-01-04',
    cancellationReason: "Admin cancelled: Ingredients unavailable",
    pickupTime: '20:00',
    status: 'Cancelled',
    total: 19.49,
    items: [
      { id: '1', name: 'Bruschetta', price: 8.99, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '7', name: 'Panna Cotta', price: 6.99, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '8', name: 'Mineral Water', price: 3.00, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    updateRequests: [],
  },
  {
    id: 'ORD-005',
    customerId: 'user-bob',
    customerName: 'Bob',
    address: bobAddress,
    orderDate: '2024-02-09',
    pickupDate: '2024-02-10',
    pickupTime: '13:00',
    status: 'Completed',
    total: 25.00,
    items: [
       { id: '4', name: 'Margherita Pizza', price: 14.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
       { id: '2', name: 'Caprese Salad', price: 10.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    reviewId: 'REV-002',
    updateRequests: [],
  },
  {
    id: 'ORD-006',
    customerId: 'user-frank',
    customerName: 'Frank',
    address: frankAddress,
    orderDate: '2024-03-19',
    pickupDate: '2024-03-20',
    pickupTime: '19:30',
    status: 'Completed',
    total: 27.50,
    items: [
      { id: '5', name: 'Grilled Salmon', price: 22.00, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
      { id: '9', name: 'Fresh Orange Juice', price: 5.50, quantity: 1, imageUrl: 'https://placehold.co/600x400.png' },
    ],
    updateRequests: [],
  },
];

export const reviews: Review[] = [
  {
    id: 'REV-001',
    orderId: 'ORD-001',
    customerName: 'Alice',
    rating: 5,
    comment: 'The Spaghetti Carbonara was absolutely divine! Best I have ever had. Will be ordering again soon!',
    date: '2023-10-27',
    adminReply: 'Thank you so much, Alice! We are thrilled you enjoyed it and look forward to serving you again.',
    isPublished: true,
  },
  {
    id: 'REV-002',
    orderId: 'ORD-005',
    customerName: 'Bob',
    rating: 4,
    comment: 'Great pizza and the Caprese salad was very fresh. The pickup process was quick and easy. Would recommend.',
    date: '2024-02-11',
    isPublished: true,
  },
  {
    id: 'REV-003',
    orderId: 'ORD-003',
    customerName: 'Charlie',
    rating: 5,
    comment: 'Delicious food and excellent service. The pre-order system is so convenient!',
    date: '2023-12-02',
    isPublished: true,
  },
    {
    id: 'REV-004',
    orderId: 'ORD-002',
    customerName: 'Diana',
    rating: 4,
    comment: 'The food was amazing, as always. A bit of a wait during pickup, but it was a busy night. Overall, a great experience.',
    date: '2023-11-16',
    adminReply: 'Thank you for your feedback, Diana! We apologize for the delay and are working to improve our pickup times during peak hours.',
    isPublished: true,
  },
  {
    id: 'REV-005',
    orderId: 'ORD-004',
    customerName: 'Eve',
    rating: 3,
    comment: 'Food was decent, but my order was slightly delayed. The staff was apologetic and friendly.',
    date: '2024-01-06',
    isPublished: false,
  }
]

export const promotions: Promotion[] = [
  {
    id: 'PROMO-1',
    title: '🎉 Welcome Offer for New Customers!',
    description: 'Get 15% off your first order with us. We are so happy to have you!',
    targetAudience: 'new',
    isActive: true,
  },
  {
    id: 'PROMO-2',
    title: 'Weekday Special for Regulars!',
    description: 'Enjoy a free dessert on your next order as a thank you for your continued support. Valid on weekdays.',
    targetAudience: 'existing',
    isActive: true,
    startDate: '2024-06-01',
    activeDays: [1, 2, 3, 4, 5], // Mon-Fri
  },
   {
    id: 'PROMO-3',
    title: 'Summer Special - All Customers',
    description: 'Get a free drink with any main course ordered this month.',
    targetAudience: 'all',
    isActive: false,
    startDate: '2023-07-01',
    endDate: '2023-07-31',
  },
];

    
