import type { MenuItem, Order } from './types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Bruschetta',
    description: 'Toasted bread with tomatoes, garlic, and basil.',
    price: 8.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'bruschetta appetizer',
    category: 'Appetizers',
  },
  {
    id: '2',
    name: 'Caprese Salad',
    description: 'Fresh mozzarella, tomatoes, and basil.',
    price: 10.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'caprese salad',
    category: 'Appetizers',
  },
  {
    id: '3',
    name: 'Spaghetti Carbonara',
    description: 'Pasta with eggs, cheese, pancetta, and pepper.',
    price: 15.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'spaghetti carbonara',
    category: 'Main Courses',
  },
  {
    id: '4',
    name: 'Margherita Pizza',
    description: 'Classic pizza with tomatoes, mozzarella, and basil.',
    price: 14.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'margherita pizza',
    category: 'Main Courses',
  },
    {
    id: '5',
    name: 'Grilled Salmon',
    description: 'Served with asparagus and lemon butter sauce.',
    price: 22.00,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'grilled salmon',
    category: 'Main Courses',
  },
  {
    id: '6',
    name: 'Tiramisu',
    description: 'Coffee-flavored Italian dessert.',
    price: 7.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'tiramisu dessert',
    category: 'Desserts',
  },
  {
    id: '7',
    name: 'Panna Cotta',
    description: 'Sweetened cream thickened with gelatin.',
    price: 6.99,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'panna cotta',
    category: 'Desserts',
  },
  {
    id: '8',
    name: 'Mineral Water',
    description: 'Still or sparkling water.',
    price: 3.00,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'water bottle',
    category: 'Drinks',
  },
    {
    id: '9',
    name: 'Fresh Orange Juice',
    description: 'Freshly squeezed orange juice.',
    price: 5.50,
    imageUrl: 'https://placehold.co/600x400.png',
    aiHint: 'orange juice',
    category: 'Drinks',
  },
];

export const orders: Order[] = [
  {
    id: 'ORD-001',
    date: '2023-10-26',
    pickupTime: '18:30',
    status: 'Completed',
    total: 32.48,
    items: [
      { id: '3', name: 'Spaghetti Carbonara', price: 15.99, quantity: 1, imageUrl: '' },
      { id: '6', name: 'Tiramisu', price: 7.50, quantity: 2, imageUrl: '' },
    ],
  },
  {
    id: 'ORD-002',
    date: '2023-11-15',
    pickupTime: '19:00',
    status: 'Confirmed',
    total: 25.00,
    items: [
      { id: '4', name: 'Margherita Pizza', price: 14.50, quantity: 1, imageUrl: '' },
      { id: '2', name: 'Caprese Salad', price: 10.50, quantity: 1, imageUrl: '' },
    ],
  },
  {
    id: 'ORD-003',
    date: '2023-12-01',
    pickupTime: '12:00',
    status: 'Pending',
    total: 27.50,
    items: [
      { id: '5', name: 'Grilled Salmon', price: 22.00, quantity: 1, imageUrl: '' },
      { id: '9', name: 'Fresh Orange Juice', price: 5.50, quantity: 1, imageUrl: '' },
    ],
  },
   {
    id: 'ORD-004',
    date: '2024-01-05',
    pickupTime: '20:00',
    status: 'Cancelled',
    total: 19.49,
    items: [
      { id: '1', name: 'Bruschetta', price: 8.99, quantity: 1, imageUrl: '' },
      { id: '7', name: 'Panna Cotta', price: 6.99, quantity: 1, imageUrl: '' },
      { id: '8', name: 'Mineral Water', price: 3.00, quantity: 1, imageUrl: '' },
    ],
  },
];
